version: '3.8'

services:
  app:
    build: .
    container_name: bimbel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - bimbel-net

  web:
    image: nginx:alpine
    container_name: bimbel-web
    ports:
      - "8082:80"       # host:container
    volumes:
      - ./:/var/www:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - bimbel-net

  db:
    image: mysql:8.0
    container_name: bimbel-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bimbel
      MYSQL_USER: bimbel
      MYSQL_PASSWORD: secret
    networks:
      - bimbel-net

networks:
  bimbel-net:
    driver: bridge
